### ISSUE TITLE
Hello, it doesnt work

### ISSUE THREAD

**Issue by Coucoucestmoiarnaud** [shmulvad/alfred-tinypng#2]
https://user-images.githubusercontent.com/76802447/103395052-b4f69500-4b5e-11eb-9fee-5bef8839a382.mov

The trigger doesnt work

**Comment by shmulvad** [comment]
Hi, thanks for the video. When selecting the Workflow in Alfred settings, can you click on the `[x]` button in the top right corner and verify that the `pythonDir` environment variable is actually the path at which you have Python 3.6+ installed?

**Comment by Coucoucestmoiarnaud** [comment]
<img width="1493" alt="Capture d’écran 2021-01-01 à 10 05 11" src="https://user-images.githubusercontent.com/76802447/103432827-dc119d00-4c18-11eb-9330-a3ff241016bb.png">

I understand how to open but i have no skill at all in coding so you speak about something i dont understand. How do i verify. that the pythonDir environment variable is actually the path at which you have Python 3.6+ installed?

**Comment by shmulvad** [comment]
It should the path at which *you* have installed Python 3.6+, not me.

The simplest fix that is likely to work is just putting in `python` or `python3`. If none of those two work, read on.

Open a terminal and type `python --version`. Make sure this is something greater than 3.6, otherwise you will need to upgrade your installation. I will not write how to upgrade but there are numerous guides available online. Next, write `which python`. This will give you the full path to your Python installation which you should put as the `pythonDir` value.
